export default [
  {
    id: 1,
    images:[ "./images/PHOTO-2022-03-14-16-27-00 (6).jpg",],
    case: "Talco Retractable Roofing Systems",
    category: "residential",
    location: "Nairobi",
    date: "10/12/2022",
    description:
      "Our retractable roofs are manufactured using European components and locally extrudedaluminium. We combine industry leading cutting and welding machinery, with craftsman-like attention to detail to produce custom made retractable roof products of the highest standards",
      more:'Using the latest design and engineering, our retractable roof range is made from architectural grade aluminium and stainless steel fixtures to ensure smooth operation and high durability. Ideal for use in private homes, courtyards, restaurants and commercial applications, our retractable roofs utilise an easy to clean waterproof fabric and 100% rain protection to create an operable outdoor room feel for an outdoor lifestyle. Cleverly designed drive system, integrated water seals and optional dimmable LED down lighting are just some of the features incorporated into our retractable roofing systems. '
  },
  
  {
    id: 2,
    case: "Home",
    images: ["../images/PHOTO-2022-03-14-16-27-00 (5).jpg",],
    category: "residential",
    location: "Nairobi",
    date: "10/12/2022",
    description: "home",
  },
  {
    id: 3,
    case: "Home",
    images: ["./images/PHOTO-2022-03-14-16-27-01 (3).jpg",],
    category: "residential",
    location: "Nairobi",
    date: "10/12/2022",
    description: "home",
  },
  {
    id: 4,
    case: "Home",
    images: ["./images/PHOTO-2022-03-14-16-27-00 (4).jpg",],
    category: "residential",
    location: "Nairobi",
    date: "10/12/2022",
    description: "home",
  },
  {
    id: 5,
    case: "Home",
    images: ["./images/PHOTO-2022-03-14-16-27-00 (6).jpg",],
    category: "leisure",
    location: "Nairobi",
    date: "10/12/2022",
    description: "home",
  },
  {
    id: 6,
    case: "Home",
    images: ["./images/PHOTO-2022-03-14-16-27-00 (4).jpg",],
    category: "leisure",
    location: "Nairobi",
    date: "10/12/2022",
    description: "home",
  },
  {
    id: 7,
    case: "Home",
    images: ["./images/PHOTO-2022-03-14-16-27-01 (3).jpg",],
    category: "leisure",
    location: "Nairobi",
    date: "10/12/2022",
    description: "home",
  },
  {
    id: 8,
    case: "Home",
    images: ["./images/PHOTO-2022-03-14-16-27-01 (4).jpg",],
    category: "leisure",
    location: "Nairobi",
    date: "10/12/2022",
    description: "home",
  },
  {
    id: 9,
    case: "Home",
    images: ["./images/PHOTO-2022-03-14-16-27-01 (6).jpg",],
    category: "commercial",
    location: "Nairobi",
    date: "10/12/2022",
    description: "home",
  },
  {
    id: 10,
    case: "Home",
    images: ["./images/PHOTO-2022-03-14-16-27-00 (4).jpg",],
    category: "commercial",
    location: "Nairobi",
    date: "10/12/2022",
    description: "home",
  },
  {
    id: 11,
    case: "Home",
    images: ["./images/PHOTO-2022-03-14-16-27-00 (5).jpg",],
    category: "commercial",
    location: "Nairobi",
    date: "10/12/2022",
    description: "home",
  },
  {
    id: 12,
    case: "Home",
    images: ["./images/PHOTO-2022-03-14-16-27-00 (4).jpg",],
    category: "commercial",
    location: "Nairobi",
    date: "10/12/2022",
    description: "home",
  },
];
